name: External Trigger

on:
  repository_dispatch:
    types: [deploy-request]

jobs:
  external:
    runs-on: ubuntu-latest
    steps:
      - name: Print payload
        run: |
         echo "Environment: ${{ github.event.client_payload.environment }}"
