name: Test Composite Action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run my custom action
        uses: ./.github/actions/setup-and-greet
        with:
          name: Rahul
          language: en